# **머신러닝 빠르게 정리하기**

# **1.환경준비**

* 라이브러리 Import

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split              # 데이터 분할
from sklearn.metrics import *                                     # 평가
from sklearn.preprocessing import StandardScaler, MinMaxScaler    # 스케일링

# **2.Regression : Advertising**

## (1) 데이터 전처리

### 1) 데이터 준비

In [2]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/advertising.csv'
data1 = pd.read_csv(path)
data1.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
# x, y 나누기
target = 'Sales'
x = data1.drop(target, axis=1)
y = data1.loc[:, target]

### 2) 가변수화

### 3) 데이터분할

In [4]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3  , random_state = 20)

### 4) Scaling
* 필요할 때만 스케일링 : KNN, SVM, K-Means, Deep Learning

In [5]:
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

## (2) 모델링
* 필요한 함수들 불러오기
* 모델 선언
* 학습
* 예측
* 성능 검증

In [6]:
# LinearRegression으로 모델링을 수행합니다.
from sklearn.linear_model import LinearRegression

### 1) 모델 선언

In [7]:
model = LinearRegression()

### 2) 학습

In [9]:
model.fit(x_train_s, y_train)

LinearRegression()

### 3) 검증 : 예측

In [10]:
pred = model.predict(x_val_s)

### 4) 검증 : 평가
만든 모델은 얼마나 정확한지 검증해 봅시다.

In [11]:
mean_absolute_error(y_val, pred)

1.5030135035019552

-----

# **3.Classification : 대학원 지원**

## (1) 데이터 전처리

### 1) 데이터 준비

In [12]:
path = "https://raw.githubusercontent.com/DA4BAM/dataset/master/Graduate_apply.csv"
data2 = pd.read_csv(path)
data2.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [13]:
# x, y 분할
target = 'admit'
x = data2.drop(target, axis=1)
y = data2.loc[:, target]

### 2) 가변수화

In [14]:
cat_cols = ['rank']
x = pd.get_dummies(x, columns = cat_cols, drop_first = True)

### 3) 데이터분할

In [15]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = .3, random_state=42)

### 4) Scaling
* 필요할 때만 스케일링 : KNN, SVM, K-Means, Deep Learning

In [16]:
scaler = MinMaxScaler()
x_train_s = scaler.fit_transform(x_train)
x_val_s = scaler.transform(x_val)

## (2) 모델링
* 필요한 함수들 불러오기
* 모델 선언
* 학습
* 예측
* 성능 검증

In [17]:
# DecisionTreeClassifier로 모델링을 수행합니다.
from sklearn.tree import DecisionTreeClassifier

### 1) 모델 선언

In [18]:
model = DecisionTreeClassifier()

### 2) 학습

In [19]:
model.fit(x_train_s, y_train)

DecisionTreeClassifier()

### 3) 검증 : 예측

In [20]:
pred = model.predict(x_val_s)

### 4) 검증 : 평가
만든 모델은 얼마나 정확한지 검증해 봅시다.

In [21]:
mean_absolute_error(y_val, pred)

0.39166666666666666